version: '2'
volumes:
  webroot:
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/sawaal.conf:/etc/nginx/conf.d/default.conf
      - webroot:/webroot/
    depends_on:
      - web
  web:
    build: .
    volumes:
      - webroot:/webroot/
    command: python sawaaljawaab.py
